# Site settings
title: Schweiz
client:
  name: Eine neue Welt erleben
  link: "http://bit.ly/2ODCrff"

se-tracking-link: "?utm_source=SE&utm_medium=hub&utm_campaign=schweiz_DE_2019"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Historische Städte mit weltstädtischem Flair – Schweizer Boutique Städte sind wie geschaffen für eine kleine Auszeit vom Alltag.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/schweiz" # the subpath of your site, e.g. /blog/
img:     "/de/schweiz/_assets/img"
css:     "/de/schweiz/_assets/css"
js:      "/de/schweiz/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
